-- PACOTE AGRUPA UM CONJUNTO DE PROCEDURES E FUNÇÕES;
-- PACOTE PODE SER COMPARTILHADO COM UM OU MAIS USUÁRIOS, DESTA FORMA TUDO QUE ESTIVER CONTIDO NO PACOTE, O USUÁRIO TERÁ ACESSO;
-- PACOTES DIMINUEM A CIRAÇÃO DE SINONIMOS. POIS COM SEU USO, BASTA CRIAR UM SINONIMO PARA O PACOTE;
-- PACOTE FACILITA A MANUTENÇÃO, POIS CASO HAJA INCREMENTO OU DECREMENTO DE FUNCTIONS OU PROCEDURES, BASTA ATULIZAR O PACOTE;

CREATE OR REPLACE PACKAGE CLIENTE_PAC
-- CREATE OR REPLACE PACKEGE NOME_PACOTE
IS
-- DECLARAÇÃO DA PROCEDURE QUE SERÁ INCLUIDA NO PACKAGE;
PROCEDURE INCLUIR_CLIENTE 
   (p_id in cliente.id%type,
    p_razao_social in cliente.razao_social%type,
    p_CNPJ cliente.CNPJ%type ,
    p_segmercado_id cliente.segmercado_id%type,
    p_faturamento_previsto cliente.faturamento_previsto%type);
-- DECLARAÇÃO DA PROCEDURE;
END;