CREATE PUBLIC SYNONYM INCLUIR_CLIENTE FOR user_dev.INCLUIR_CLIENTE;
-- CREATE PUBLIC NYNONYM NOME_SINONIMO FOR NOME_USER_OWNER.NOME_PROCEDURE/TABLE/FUNCTION...
-- PUBLIC PARA QUEM TEM O PRIVILÉGIO DE ACESSO
-- BOA PRÁTICA: COLOCAR O NOME DO SINONIMO = O NOME DO COMPONENTE;

CREATE PUBLIC SYNONYM ATUALIZAR_CLI_SEG_MERCADO FOR user_dev.ATUALIZAR_CLI_SEG_MERCADO;
CREATE PUBLIC SYNONYM ATUALIZAR_FATURAMENTO_PREVISTO FOR user_dev.ATUALIZAR_FATURAMENTO_PREVISTO;
CREATE PUBLIC SYNONYM EXCLUIR_CLIENTE FOR user_dev.EXCLUIR_CLIENTE;

CREATE PUBLIC SYNONYM CLIENTE FOR user_dev.CLIENTE;