CREATE OR REPLACE PACKAGE EXCEPTION_PAC

IS

    E_NULL EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_NULL, -1400);
    --                     VARIÁVEL, N ERRO ORACLE. ERRO NÃO CONSTA NA DOCUMENTAÇÃO. É NECESSÁRIO FORÇA-LO PARA VER;
    E_FK EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_FK, -2291);

END;

-- INCLUIR A EXCEPTION DO PACKAGE EM UMA PROCEDURE:
--CREATE OR REPLACE ...
--IS
--BEGIN
--EXCEPTION
--    WHEN EXCEPTION_PAC.E_NULL THEN
--    raise_application_error (-20012,'Preenchimento de campo obrigatório');
--END;