GRANT EXECUTE ON ATUALIZAR_CLI_SEG_MERCADO TO user_app;
GRANT EXECUTE ON ATUALIZAR_FATURAMENTO_PREVISTO TO user_app;
GRANT EXECUTE ON EXCLUIR_CLIENTE TO user_app;
GRANT EXECUTE ON INCLUIR_CLIENTE TO user_app;
-- DA PERMISSÃO DE EXECUTAR PROCEDURES AO user_app

GRANT SELECT ON CLIENTE TO user_app;
-- DA PRECISSÃO DE SELECT AO USUÁRIO user_app