DECLARE
    CURSOR cur_CLIENTE IS SELECT ID FROM CLIENTE;
--  CURSOR É UMA VARIÁVEL. cur_ É uma boa prática para declaração de cursor. SELECT CONSULTA DA TABELA QUE QUERO;
-- O resultado do select tem seus dados associados a variável cur_cliente;

    v_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%TYPE := 4;
    v_ID CLIENTE.ID%TYPE;
-- VARIÁVEIS DE TRABALHO PARA PERCORRER O CURSOR;

BEGIN
    OPEN cur_CLIENTE;
-- ABRIR O CURSOR. TRAZENDO O RESULTADO DO SELECT E JOGAR ELE EM MEMÓRIA;

    LOOP
        FETCH cur_CLIENTE INTO v_ID;
--  NUMERO DE VARIÁVEIS APÓS O INTO DEVE SER IGUAL A QUANTIDADE DE COLUNAS NO SELECT.
--  COMO O FETCH VAI BUSCAR DADOS DE DUAS COLUNAS DISTINTAS, É NECESSÁRIO TER DUAS VARIÁVEIS PARA ARMAZENAR SEUS VALORES;

    EXIT WHEN cur_CLIENTE%NOTFOUND;
-- SAIR DO LOOP QUANDO AO DAR O FETCH, NÃO ENCONTRAR NENHUMA LINHA;
    ATUALIZAR_CLI_SEG_MERCADO(p_SEGMERCADO_ID => v_SEGMERCADO_ID, p_ID => v_ID);

    END LOOP;
    
    CLOSE cur_CLIENTE;
-- FECHAR O CURSOR PARA TIRAR ELE DA MEMORIA;
END;

SELECT * FROM CLIENTE;