CREATE PROCEDURE INCLUIR_SEGMERCADO (p_ID IN NUMBER, p_DESCRICAO IN VARCHAR2)
--CREATE PROCEDURE NOME_PROCEDURE (PARÂMETROS)
IS
-- DECLARAR AS VARIÁVEIS USADAS NA PROCEDURE;
BEGIN
    INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (p_ID, UPPER(p_DESCRICAO));
    COMMIT;
END;


EXECUTE INCLUIR_SEGMERCADO(4, 'Farmaceuticos');
-- EXECUTE NOME_PROCEDURE (PARÂMETRO 1, PARÂMETRO 2);

SELECT * FROM SEGMERCADO
ORDER BY ID ASC;
BEGIN
INCLUIR_SEGMERCADO (5, 'Industrial');
END;
-- OUTRA FORMA DE EXECUTAR UMA PROCEDURE;