CREATE OR REPLACE PROCEDURE FORMATA_CNPJ
(p_CNPJ IN OUT CLIENTE.CNPJ%TYPE)
-- CNPJ_SAIDA E DO TIPO OUT PARA CONSEGUIR SAIR DA PROCEDURE COM UM VALOR;
IS
BEGIN
    p_CNPJ := SUBSTR(p_CNPJ, 1,3) || '/' || SUBSTR(p_CNPJ, 4,2);
END;
