CREATE OR REPLACE FUNCTION OBTER_DESCRICAO_SEGMERCADO
    (p_ID IN SEGMERCADO.ID%TYPE)
        RETURN SEGMERCADO.DESCRICAO%TYPE
-- INFORMA QUAL TIPO DE DADO ELA DEVE RETORNAR
IS
    v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
-- DEVO DECLARAR POIS ELA NÃO TEM INICIALIZAÇÃO NA FUNÇÃO

BEGIN
    SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = p_ID;
                                                        -- IGUALDADE É O PARÂMETRO DA FUNCAO;
    RETURN v_DESCRICAO;
END;










SET SERVEROUTPUT ON;
-- HABILITA O DBMS OUTPUT

DECLARE
    v_ID SEGMERCADO.ID%TYPE := 1;
    v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
-- VARIÁVEL NÃO RECEBE VALOR INICIAL, POIS RECEBERÁ FUTURAMENTE;
BEGIN
    SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = v_ID;
-- SELECT NOME_CAMPO PASSANDO O VALOR DELE PARA A VARIÁVEL v_DESCRICAO DA
-- TABELA SEGMERCADO ONDE O ID = VALOR PASSADO A VARIÁVEL v_ID;

    DBMS_OUTPUT.PUT_LINE(v_DESCRICAO);
-- EXIBE O RESULTADO DA VARIÁVEL PASSADA NO PARÂMETRO;
    

END;
