EXECUTE INCLUIR_CLIENTE (1, 'MERCEARIA XYZ', '89231', 1, 10000);
EXECUTE INCLUIR_CLIENTE (6, 'FARMACIA QWE', '90000', 1, 80000);
EXECUTE INCLUIR_CLIENTE (3, 'MERCADINHO JKL', '78963', 1, 70000);
EXECUTE INCLUIR_CLIENTE (4, 'PADARIA BLS', '45600', 1, 60000);
EXECUTE INCLUIR_CLIENTE (5, 'TAVERNA SDF', '45602', 1, 10000);
EXECUTE INCLUIR_CLIENTE (2, 'SUPERMERCAO IJK', '67890', 1, 90000);

SELECT * FROM CLIENTE
ORDER BY ID ASC;

CREATE OR REPLACE PROCEDURE ATUALIZAR_CLI_SEG_MERCADO
(p_ID CLIENTE.ID%TYPE, p_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%TYPE)
IS
BEGIN
UPDATE CLIENTE SET SEGMERCADO_ID = p_SEGMERCADO_ID
WHERE ID = p_ID;
COMMIT;
END;

EXECUTE ATUALIZAR_CLI_SEG_MERCADO (3, 2);
-- 3 == PRIMEIRO PARÂMETRO = ID.  2 == SEGUNDO PARÂMETRO, SEGMERCADO_ID A SER ALTERADO;

DECLARE
    v_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%TYPE := 1;
    v_I NUMBER(3) := 1;
BEGIN
    LOOP
    --INÍCIO LOOP
        ATUALIZAR_CLI_SEG_MERCADO(v_I, v_SEGMERCADO_ID);
        v_I := v_I + 1;
    EXIT WHEN
    -- CODIÇÃO DE SAÍDA
        v_I > 6;
    END LOOP;
    --FIM LOOP
END;

