SELECT * FROM CLIENTE;

DECLARE 
    v_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%TYPE := 1;
BEGIN
    FOR v_ID IN 1..6 LOOP
    -- variável v_1 começa em 1 e vai até 6
    ATUALIZAR_CLI_SEG_MERCADO(p_ID => v_ID, p_SEGMERCADO_ID => v_SEGMERCADO_ID);
    --                NOME_PARÂMETRO, VALOR_RECEBIDO
    END LOOP;
END;
