DECLARE 
v_ID SEGMERCADO.ID%TYPE := 2;
-- %TYPE, INFROMA QUE ESSA VARIÁVEL É DO MESMO TIPO
--DO CAMPO ID DECLARADO NA TABELA SEGMERCADO
v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Atacado';
-- NOME_VARIÁVEL  NOME_TABELA  NOME_CAMPO_TABELA %TYPE RECEBE 'VALOR'
BEGIN
    INSERT INTO SEGMERCADO
    (ID, DESCRICAO)
    VALUES
    (v_ID, upper(v_DESCRICAO));
    -- upper garante que o campo seja inputado TODO EM MAIÚSCULO
    COMMIT;
END;
