--UTLDTREE.SQL SEARCH AT ORACLA DEVELOPER FOLDERS;
-- COPY CODE AND EXECUTE WITH TABLE OWNER USER;

EXECUTE DEPTREE_FILL('TABLE','user_dev', 'CLIENTE');
-- 3 PARÂMETROS: TIPO DO OBJETO A ANALISAR, USUÁRIO DONO DO OBJETO, NOME DO OBJETO;
-- ANALISA OS DADOS DA TABELA E INCLUI NO DEPTREE;

SELECT * FROM DEPTREE_TEMPTAB;

SELECT NESTED_LEVEL, SCHEMA, TYPE, NAME FROM DEPTREE ORDER BY SEQ#;
-- NESTED_LEVEL == PROFUNDIDADE DO CLINETE. RECLAÇÃO AO FOCO DA ANÁLISE;

EXECUTE DEPTREE_FILL ('PROCEDURE', 'user_dev', 'INCLUIR_CLIENTE');
-- ANALISA A ÁRVORE DA PROCEDURE INCLUIR_CLIENTE;
SELECT NESTED_LEVEL, SCHEMA, TYPE, NAME FROM DEPTREE ORDER BY SEQ#;