SET SERVEROUTPUT ON;
-- PODER EXIBIR A MENSAGEM DO DBMS_OUTPUT;

DECLARE
    CURSOR cur_CLIENTE IS SELECT ID, RAZAO_SOCIAL FROM CLIENTE;
--  CURSOR É UMA VARIÁVEL. cur_ É uma boa prática para declaração de cursor. SELECT CONSULTA DA TABELA QUE QUERO;
-- O resultado do select tem seus dados associados a variável cur_cliente;

    v_ID CLIENTE.ID%TYPE;
    v_RAZAO_SOCIAL CLIENTE. RAZAO_SOCIAL%TYPE;
-- VARIÁVEIS DE TRABALHO PARA PERCORRER O CURSOR;

BEGIN
    OPEN cur_CLIENTE;
-- ABRIR O CURSOR. TRAZENDO O RESULTADO DO SELECT E JOGAR ELE EM MEMÓRIA;

    LOOP
        FETCH cur_CLIENTE INTO v_ID, v_RAZAO_SOCIAL;
--  NUMERO DE VARIÁVEIS APÓS O INTO DEVE SER IGUAL A QUANTIDADE DE COLUNAS NO SELECT.
--  COMO O FETCH VAI BUSCAR DADOS DE DUAS COLUNAS DISTINTAS, É NECESSÁRIO TER DUAS VARIÁVEIS PARA ARMAZENAR SEUS VALORES;

    EXIT WHEN cur_CLIENTE%NOTFOUND;
-- SAIR DO LOOP QUANDO AO DAR O FETCH, NÃO ENCONTRAR NENHUMA LINHA;

    DBMS_OUTPUT.PUT_LINE('ID: ' || v_ID);
    DBMS_OUTPUT.PUT_LINE('RAZAO SOCIAL: ' || v_RAZAO_SOCIAL);
-- CASO ENCONTRE LINHAS, MOSTRAR NO OUTPUT  O VALOR RECEBIDO PELA v_ID e v_RAZAO_SOCIAL; 
    END LOOP;
    
    CLOSE cur_CLIENTE;
-- FECHAR O CURSOR PARA TIRAR ELE DA MEMORIA;
-- 
END;