VARIABLE g_DESCRICAO VARCHAR2(100)
-- g Padrão para variáveis declaradas no Oracle Developer;
EXECUTE :g_DESCRICAO:=OBTER_DESCRICAO_SEGMERCADO(3)
-- g_DESCRICAO RECEBER O VALOR DO CAMPO DESCRIÇÃO 
-- RETORNADO PELA FUNÇÃO OBTER_DESCRICAO_SEGMERCADO(PARÂMETRO),
PRINT g_DESCRICAO


-- CODIGO PL;SQL
SET SERVEROUTPUT ON

DECLARE
    v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
-- VARIÁVEL QUE RECEBERÁ O RETORNO DA FUNÇÃO
BEGIN
    v_DESCRICAO := OBTER_DESCRICAO_SEGMERCADO(2);
 -- ATRIBUIR UM VALOR A VARIÁVEL
 -- RECEBERTÁ O RETORNO DA FUNÇÃO CHAMADA

    DBMS_OUTPUT.PUT_LINE('A descrição do segmento de mercado é:' || v_DESCRICAO);
-- COMANDO PARA IMPRIMIR O RESULTADO NO SCRIPT OUTPUT
-- TEXTO CONTATENADO COM O VALOR DA VARIÁVEL;
END;
