CREATE OR REPLACE FUNCTION CATEGORIA_CLIENTE
    (p_FATURAMENTO_PREVISTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE)
    RETURN CLIENTE.CATEGORIA%TYPE

IS
    v_CATEGORIA CLIENTE.CATEGORIA%TYPE;

BEGIN

        IF  p_FATURAMENTO_PREVISTO < 10000 THEN
        v_CATEGORIA := 'PEQUENO';
    ELSIF
        p_FATURAMENTO_PREVISTO < 50000 THEN
        v_CATEGORIA := 'MÉDIO';
    ELSIF
        p_FATURAMENTO_PREVISTO < 100000 THEN
        v_CATEGORIA := 'MÉDIO-GRANDE';
    ELSE
        v_CATEGORIA := 'GRANDE'; 
    END IF;
    
    RETURN v_CATEGORIA;

END;


VARIABLE g_CATEGORIA VARCHAR2(100);
EXECUTE :g_CATEGORIA := CATEGORIA_CLIENTE(110000);
PRINT g_CATEGORIA;