SELECT * FROM CLIENTE;

DECLARE 
    v_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%TYPE := 3;
BEGIN
    FOR v_ID IN 1..6 LOOP
    -- variável v_1 começa em 1 e vai até 6
    ATUALIZAR_CLI_SEG_MERCADO(v_ID, v_SEGMERCADO_ID);
    END LOOP;
END;
