SET SERVEROUTPUT ON;

DECLARE
    v_FATURAMENTO_PREVISTO CLIENTE.FATURAMENTO_PREVISTO%TYPE := 12000;
    v_CATEGORIA CLIENTE.CATEGORIA%TYPE;

    
BEGIN
    IF  v_FATURAMENTO_PREVISTO < 10000 THEN
        v_CATEGORIA := 'PEQUENO';
    ELSIF
        v_FATURAMENTO_PREVISTO < 50000 THEN
        v_CATEGORIA := 'MÉDIO';
    ELSIF
        v_FATURAMENTO_PREVISTO < 100000 THEN
        v_CATEGORIA := 'MÉDIO-GRANDE';
    ELSE
        v_CATEGORIA := 'GRANDE'; 
    END IF;
-- E L S I F sem o E DO elsE

    DBMS_OUTPUT.PUT_LINE('A categoria é ' || v_CATEGORIA);
    
END;